apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-photos
  namespace: fc
spec:
  storageClassName: local-path
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
